version: '3'

services:
  video-server:
    image: ghcr.io/nntamp/nancy-video-server:latest
    container_name: video-server
    ports:
      - "8080:80"
    volumes:
      - ./videos:/usr/share/nginx/videos
      - ./logs:/var/log/nginx
    environment:
      # video storage URL should be placed HERE
      - VIDEO_SOURCE_URL=${VIDEO_SOURCE_URL}
    restart: unless-stopped