version: '3'

services:
  video-server:
    image: test
    container_name: video-server
    ports:
      - "8080:80"
    volumes:
      - ./videos:/usr/share/nginx/videos
      - ./logs:/var/log/nginx
    environment:
      # video storage URL should be placed HERE
      - VIDEO_SOURCE_URL=${VIDEO_SOURCE_URL}
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    restart: unless-stopped
    depends_on:
      - nancy-grpc-server-side
  nancy-grpc-client-side:
    image: nancy-grpc
    container_name: nancy-grpc-client-side
    ports:
      - "8000:8000"
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
      - GRPC_HOST=${GRPC_HOST:-10.10.10.40}
      - GRPC_PORT=${GRPC_PORT:-50001}
      - UVICORN_HOST=${UVICORN_HOST:-0.0.0.0}
      - UVICORN_PORT=${UVICORN_PORT:-8000}
      - API_TITLE=${API_TITLE:-DLT Gateway REST API client-side}
  nancy-grpc-server-side:
    image: nancy-grpc
    container_name: nancy-grpc-server-side
    ports:
      - "8001:8000"
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
      - GRPC_HOST=${GRPC_HOST:-10.10.10.40}
      - GRPC_PORT=${GRPC_PORT:-50000}
      - UVICORN_HOST=${UVICORN_HOST:-0.0.0.0}
      - UVICORN_PORT=${UVICORN_PORT:-8000}
      - API_TITLE=${API_TITLE:-DLT Gateway REST API server-side}
