version: '3'

services:
  video-server:
    build: .
    container_name: video-server
    ports:
      - "8080:80"
    volumes:
      - ./videos:/usr/share/nginx/videos
      - ./logs:/var/log/nginx
    restart: unless-stopped