version: '3'

services:
  video-server:
    build: .
    container_name: video-server
    ports:
      - "8080:80"
    volumes:
      - ./videos:/usr/share/nginx/videos
      - ./logs:/var/log/nginx
    environment:

      # Multiple videos (comma-separated)
      - VIDEO_SOURCE_URL=https://drive.google.com/file/d/1SLjNNWPgGoCbjtxyelZl4QZIGtXoTAf0/view?usp=sharing,https://drive.google.com/file/d/1dNkhvsnTSdVmVCgvaa8_YEY8LIMxxB0D/view?usp=sharing

    restart: unless-stopped